pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "my-react-app"
    }

    stages {
        stage('Clone repository') {
            steps {
                git url: 'https://github.com/Mayank-kr-sh/Docker-Demo', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}","my-react-app")
                }
            }
        }

        stage('Test') {
    steps {
        dir('my-react-app') {
            sh 'npm install'
            sh 'npm test -- --watchAll=false || true' // Allow pipeline to continue even if tests fail
        }
    }
}


        stage('Deploy') {
            steps {
                script {
                    docker.image("${DOCKER_IMAGE}").run("-p 3000:80")
                }
            }
        }
    }
}
